/* Prototype-only interaction and layout checks; no application routes are used. */
const { chromium } = require('@playwright/test');
const { default: AxeBuilder } = require('@axe-core/playwright');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext({ viewport: { width: 1600, height: 1050 }, reducedMotion: 'reduce' });
  const page = await context.newPage();
  const errors = [], requests = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (/\/api\//.test(request.url())) requests.push(request.url()); });
  const folder = __dirname;
  try {
    await page.goto(pathToFileURL(path.join(folder, 'index.html')).href);
    await page.getByRole('heading', { name: 'People', exact: true }).waitFor();
    assert.equal(await page.locator('.person-row').count(), 10);
    await page.screenshot({ path: path.join(folder, '01-people-desktop.png') });
    await page.getByRole('button', { name: 'Next page', exact: true }).click();
    assert.match(await page.locator('#range').textContent(), /Page 2/);
    await page.getByLabel('Search people', { exact: true }).fill('alexchen');
    assert.equal(await page.locator('.person-row').count(), 1);
    await page.getByRole('button', { name: 'Alex Chen', exact: true }).click();
    await page.getByRole('heading', { name: 'Alex Chen', exact: true }).waitFor();
    await page.screenshot({ path: path.join(folder, '02-person-profile.png') });
    await page.getByRole('button', { name: 'Close profile', exact: true }).click();
    await page.getByLabel('Search people', { exact: true }).fill('');
    await page.getByRole('button', { name: 'Invite person', exact: true }).click();
    await page.getByLabel('UBC email or CWL', { exact: true }).fill('rachelw');
    await page.getByLabel('TA', { exact: true }).check();
    await page.getByLabel('View student analytics', { exact: true }).uncheck();
    await page.screenshot({ path: path.join(folder, '03-invite-role.png') });
    await page.getByRole('button', { name: 'Create invitation', exact: true }).click();
    await page.getByRole('button', { name: 'Rachel Wu', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Change role for Rachel Wu', exact: true }).click();
    await page.getByLabel('Instructor', { exact: true }).check();
    await page.screenshot({ path: path.join(folder, '04-change-role.png') });
    await page.getByRole('button', { name: 'Save role', exact: true }).click();
    await page.getByLabel('Search people', { exact: true }).fill('rachelw');
    assert.equal(await page.locator('.role-edit').textContent(), 'Instructor⌄');
    await page.getByRole('button', { name: 'Ban', exact: true }).click();
    await page.getByLabel('Internal reason', { exact: false }).fill('Access paused pending a course meeting.');
    await page.screenshot({ path: path.join(folder, '05-course-ban.png') });
    await page.getByRole('button', { name: 'Ban from course', exact: true }).click();
    assert.match(await page.locator('.person-row').textContent(), /Banned/);
    await page.getByRole('button', { name: 'Unban', exact: true }).click();
    await page.getByRole('button', { name: 'Restore access', exact: true }).click();
    assert.match(await page.locator('.person-row').textContent(), /Active/);
    await page.getByLabel('Search people', { exact: true }).fill('John Faculty');
    assert.equal(await page.getByRole('button', { name: 'Change role for John Faculty', exact: true }).isDisabled(), true);
    assert.equal(await page.getByRole('button', { name: 'Ban', exact: true }).count(), 0);
    await page.getByRole('button', { name: 'Invite person', exact: true }).click();
    await page.getByLabel('UBC email or CWL', { exact: true }).fill('new.student@ubc.ca');
    await page.getByRole('button', { name: 'Create invitation', exact: true }).click();
    assert.equal(await page.getByRole('tab', { name: /Invitations/ }).getAttribute('aria-selected'), 'true');
    await page.getByRole('button', { name: 'New Student', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Change role for New Student', exact: true }).click();
    await page.getByLabel('TA', { exact: true }).check();
    await page.getByRole('button', { name: 'Save role', exact: true }).click();
    assert.match(await page.locator('.person-row').first().textContent(), /TA/);
    await page.getByRole('tab', { name: /Registration codes/ }).click();
    await page.getByLabel('Rows per page', { exact: true }).selectOption('25');
    await page.getByLabel('Number of codes', { exact: true }).fill('30');
    await page.getByRole('button', { name: 'Generate codes', exact: true }).click();
    assert.equal(await page.locator('.code-row').count(), 25);
    await page.getByRole('button', { name: 'Next page', exact: true }).click();
    assert.equal(await page.locator('.code-row').count(), 18);
    await page.locator('.code-row').first().getByRole('button', { name: 'Delete', exact: true }).click();
    await page.getByRole('button', { name: 'Delete record', exact: true }).click();
    assert.equal(await page.locator('.code-row').count(), 17);
    await page.getByRole('button', { name: 'Import Gradebook', exact: true }).click();
    await page.getByRole('button', { name: 'Load demo Gradebook', exact: true }).click();
    assert.equal(await page.getByRole('button', { name: 'Import students', exact: true }).isDisabled(), true);
    await page.screenshot({ path: path.join(folder, '06-gradebook-preview.png') });
    await page.locator('#import-confirmation').check();
    await page.getByRole('button', { name: 'Import students', exact: true }).click();
    await page.getByLabel('Search people', { exact: true }).fill('Morgan Brooks');
    await page.getByRole('button', { name: 'Morgan Brooks', exact: true }).waitFor();
    await page.getByLabel('Prototype viewing role', { exact: true }).selectOption('instructor');
    assert.equal(await page.getByRole('button', { name: 'Invite person', exact: true }).isDisabled(), true);
    assert.equal(await page.locator('.role-edit').isDisabled(), true);
    await page.getByRole('button', { name: 'Reset demo', exact: true }).click();
    await page.getByLabel('Filter role', { exact: true }).selectOption('Student');
    await page.getByLabel('Search people', { exact: true }).fill('no such person');
    await page.getByRole('heading', { name: 'No matching records', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Clear filters', exact: true }).click();
    assert.equal(await page.locator('.person-row').count(), 10);
    const scan = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa']).analyze();
    assert.deepEqual(scan.violations.map(value => ({ id: value.id, nodes: value.nodes.map(node => node.target) })), []);
    await page.getByRole('button', { name: 'Toggle dark mode', exact: true }).click();
    const darkScan = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa']).analyze();
    assert.deepEqual(darkScan.violations.map(value => ({ id: value.id, nodes: value.nodes.map(node => node.target) })), []);
    await page.screenshot({ path: path.join(folder, '07-people-dark.png') });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({ path: path.join(folder, '08-people-mobile.png') });
    await page.getByRole('button', { name: 'Invite person', exact: true }).click();
    await page.screenshot({ path: path.join(folder, '09-invite-mobile.png') });
    await page.getByRole('button', { name: 'Close dialog', exact: true }).click();
    assert.deepEqual(errors, []); assert.deepEqual(requests, []);
    process.stdout.write('Prototype interactions, pagination, owner protection, mobile layout and light/dark accessibility passed. No API requests.\n');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
